import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import  buildClient  from "@/lib/api/build-client";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}


RootLayout.getInitialProps = async (appContext) => {
  const client = buildClient(appContext.ctx)
	const { data } = await client.get('/api/users/currentuser')

	let pageProps = {}
	if (appContext.Component.getInitialProps) {
		pageProps = await appContext.Component.getInitialProps(
			appContext.ctx,
			client,
			data.currentUser
		)
	}

	return {
		pageProps,
		...data,
	}
}


export default RootLayout;