import type { Metadata } from 'next'

import './globals.css'
import { ThemeProvider } from './themeProvider'
import { Providers } from './StoreProvider'
import { Toaster } from '@/components/ui/toaster'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<Providers>
				<body className={`antialiased`}>
					<ThemeProvider
						attribute="class"
						defaultTheme="dark"
						enableSystem
						disableTransitionOnChange
					>
						{children}
					</ThemeProvider>
					<Toaster />
				</body>
			</Providers>
		</html>
	)
}

export default RootLayout
