apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: us-central1-docker.pkg.dev/ticketing-dev-250401/tixkart/aditya250401-ticketing-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: us-central1-docker.pkg.dev/ticketing-dev-250401/tixkart/aditya250401-ticketing-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: us-central1-docker.pkg.dev/ticketing-dev-250401/tixkart/aditya250401-ticketing-tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: us-central1-docker.pkg.dev/ticketing-dev-250401/tixkart/aditya250401-ticketing-orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: us-central1-docker.pkg.dev/ticketing-dev-250401/tixkart/aditya250401-ticketing-expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: us-central1-docker.pkg.dev/ticketing-dev-250401/tixkart/aditya250401-ticketing-payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
