name: deploy-manifests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save 3efb1cda-3603-47c4-bb48-7c7aef673b04
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3

#       - id: 'auth'
#         uses: 'google-github-actions/auth@v1'
#         with:
#           credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_INFRA }}'

#       - name: install the gcloud cli
#         uses: google-github-actions/setup-gcloud@v2
#         with:
#           project_id: ticketing-dev-250401
#           install_components: 'gke-gcloud-auth-plugin'

#       - name: Apply
#         run: |-
#           gcloud container clusters get-credentials cluster-1 --zone us-central1-c --project bigbeardevs
#           kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
