name: deploy-auth

on:
  push:
    branches:
      - main
    paths:
      - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: cd auth && docker build -t aditya250401/ticketing-auth .
      - run: docker push aditya250401/ticketing-auth
      # - uses: digitalocean/action-doctl@v2
      #   with:
      #     token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      # - run: doctl kubernetes cluster kubeconfig save tixkart-bigbeardevs
      # - run: kubectl rollout restart deployment auth-depl
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: code checkout
#         uses: actions/checkout@v2

# Deploy on GKE
#       - id: 'auth'
#         uses: 'google-github-actions/auth@v1'
#         with:
#           credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

#       - name: install the gcloud cli
#         uses: google-github-actions/setup-gcloud@v2
#         with:
#           project_id: ticketing-dev-250401
#           install_components: 'gke-gcloud-auth-plugin'

#       - name: build and push the docker image
#         env:
#           GOOGLE_PROJECT: ticketing-dev-250401
#         run: |
#           gcloud auth configure-docker us-central1-docker.pkg.dev
#           docker build -t aditya250401-ticketing-auth ./auth
#           docker push aditya250401-ticketing-auth:latest
