name: deploy-manifests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_INFRA }}'

      - name: Apply
        run: |-
          kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod

